
spring.application.name=API-Gatway
server.port=8085


# Eureka Server
eureka.client.service-url.defaultZone=http://localhost:8761/eureka

# Register API Gateway with Eureka
eureka.client.register-with-eureka=true

# Fetch all registered services
eureka.client.fetch-registry=true


spring.cloud.gateway.routes[0].id=USER-SERVICE
spring.cloud.gateway.routes[0].uri=lb://USER-SERVICE
spring.cloud.gateway.routes[0].predicates[0]=Path=/userservice,/userservice/**

spring.cloud.gateway.routes[1].id=HOTEL-SERVICE
spring.cloud.gateway.routes[1].uri=lb://HOTEL-SERVICE
spring.cloud.gateway.routes[1].predicates[0]=Path=/hotelservice/**

spring.cloud.gateway.routes[2].id=RATING-SERVICE
spring.cloud.gateway.routes[2].uri=lb://RATING-SERVICE
spring.cloud.gateway.routes[2].predicates[0]=Path=/ratingservice/**

